// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riseyofmyacrswrixvna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpc2V5b2ZteWFjcnN3cml4dm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTU1NjUsImV4cCI6MjA2MDk3MTU2NX0.Yhv6sRvQ6-eQpUyiIzG5a0mm0om9GLn3myFos0r5Uq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);