// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpgwetwusphmqtxmsryp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwZ3dldHd1c3BobXF0eG1zcnlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODI1NjQsImV4cCI6MjA2NTE1ODU2NH0.Y4vHjXMGerxykawrx-GLe9B6iwGRP0nPOScxUUkdWrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);